name: scheduled-worker

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes
  workflow_dispatch: {}     # allow manual runs

jobs:
  run-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run worker (drain mode)
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
          EMBEDDING_MODEL_NAME: ${{ secrets.EMBEDDING_MODEL_NAME }}
          EMBEDDING_DEVICE: ${{ secrets.EMBEDDING_DEVICE }}
          TOKENIZER_NAME: ${{ secrets.TOKENIZER_NAME }}
        run: |
          python worker.py
